config/routes.rb
PhotographyStudio::Application.routes.draw do
  resources :announcements
  resources :albums
  resources :images
  get "sessions/new"
  get "sessions/create"

  controller :Users do
    get "admin_edit" => :edit
    post "admin_edit" => :update
    get "admin_show" => :show
    put "admin_edit" => :update
  end
  controller :images do
    get "del_image" => :destroy
  end
 controller :Sessions do
   post "/sessions/new" => :create
   get "login" => :new
   post "login" => :create
   get "logout" => :destroy
 end

  controller :Home do
   get "/home" => :home_page

  end
  controller :FlashHome do
    get "flash" =>:flash_home
    get "/music" => :music
    get "/error" => :error
  end
  controller :albums do
    get "delete_album" => :destroy
  end
  controller :PortfolioTwo do
    get "/home" => :home_page
    get "/show" => :show
  end
  controller :announcements do
    get "delete_message" => :destroy
  end

  root :to => 'flash_home#flash_home',:as=>"flash"

  match "*a" => "flash_home#error"
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :content, :name,:summary
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # GET /announcements
  # GET /announcements.json
  before_filter :authorize ,:except => [:index,:show]
  def index
    @announcements = Announcement.order('created_at desc').paginate :page=>params[:page]||1,:per_page=>9
    @announcement = Announcement.find_by_id(1)
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])
    @announcements = Announcement.all
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(params[:announcement])
    if Announcement.all.first.nil?
     @announcement.id = 1
    end


    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def return_y_m announcement

  end
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement,:html => {:size=>"60%"}) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="fe">
  <div class="edit_field">
    <%= f.label :name , "标题" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="edit_field">
    <%= f.label :content ,"内容" %><br />
    <%= f.text_area :content  %>
  </div>
  <div class="edit_field">
    <%= f.label :summary ,"内容简介" %><br />

    <%= f.text_field :summary %>
  </div>
  <div class="actions">
    <%= f.submit "上传动态"%>
  </div>
    <%= link_to '退出编辑', announcements_path %>
 </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<!--<div id="site_content">-->
<div id="left_content">
  <div id="blog_container">

    <% unless @announcement.nil? %>
        <div class="blog"><h2><%= @announcement.created_at.strftime("%y-%m") %></h2>

          <h3><%= @announcement.created_at.strftime("%e") %></h3></div>

        <h4 class="select"><%= link_to @announcement.name, announcement_path(:id => @announcement.id) %></h4>

        <p><%= @announcement.summary %> <%= link_to "更多", announcement_path(:id => @announcement.id) %>
          <% unless find_user.nil? %>
              <%= link_to "删除", delete_message_path(:id => @announcement.id) %>
          <% end %>
        </p>
    <% end %>

    <% @announcements.each do |announcement| %>
        <% if announcement.name != @announcement.name %>
            <div class="blog"><h2><%= announcement.created_at.strftime("%y-%m") %></h2>

              <h3><%= announcement.created_at.strftime("%e") %></h3></div>
            <h4><%= link_to announcement.name, announcement_path(:id => announcement.id) %></h4>

            <p><%= announcement.summary %> <%= link_to "更多", announcement_path(:id => announcement.id) %>
              <% unless find_user.nil? %>
                  <%= link_to "删除", delete_message_path(:id => announcement.id) %>
              <% end %>
            </p>
        <% end %>
    <% end %>
  </div>
</div>
<div id="right_content">
  <% unless @announcement.nil? %>
      <div id="blog_text">
        <h1><%= @announcement.name %> </h1>
        <%= @announcement.content %>
      </div>
  <% end %>
</div>
<%= will_paginate @announcements, :prev_label => '上一页', :next_label => '下一页' %>

app/views/announcements/new.html.erb
<%= render 'form' %>

app/views/announcements/show.html.erb
<!--<div id="site_content">-->
<div id="left_content">
  <div id="blog_container">
    <% @announcements.each do |announcement| %>
        <% if announcement.name == @announcement.name%>
        <div class="blog"><h2><%= announcement.created_at.strftime("%y-%m")%></h2>

          <h3><%= announcement.created_at.strftime("%e")%></h3></div>

            <h4 class="select"><%= link_to announcement.name, announcement_path(:id=>announcement.id) %></h4>

            <p><%= announcement.summary%> <%= link_to "更多",announcement_path(:id=>announcement.id) %>
              <% unless find_user.nil? %>
                  <%= link_to "删除", delete_message_path(:id => announcement.id) %>
              <% end %>
            </p>
        <% else %>
            <div class="blog"><h2><%= announcement.created_at.strftime("%y-%m")%></h2>

              <h3><%= announcement.created_at.strftime("%e")%></h3></div>
            <h4><%= link_to announcement.name, announcement_path(:id=>announcement.id)%></h4>
            <p><%= announcement.summary%> <%= link_to "更多",announcement_path(:id=>announcement.id) %>
              <% unless find_user.nil? %>
                  <%= link_to "删除", delete_message_path(:id => announcement.id) %>
              <% end %>
            </p>
        <% end %>
    <% end %>
  </div>
</div>
<div id="right_content">
  <div id="blog_text">
    <h1><%=@announcement.name %> </h1>
    <%=@announcement.content %>
  </div>
</div>
<!--</div>-->
<!-- end content -->