config/routes.rb
PhotographyStudio::Application.routes.draw do
  resources :announcements
  resources :albums
  resources :images
  get "sessions/new"
  get "sessions/create"

  controller :Users do
    get "admin_edit" => :edit
    post "admin_edit" => :update
    get "admin_show" => :show
    put "admin_edit" => :update
  end
  controller :images do
    get "del_image" => :destroy
  end
 controller :Sessions do
   post "/sessions/new" => :create
   get "login" => :new
   post "login" => :create
   get "logout" => :destroy
 end

  controller :Home do
   get "/home" => :home_page

  end
  controller :FlashHome do
    get "flash" =>:flash_home
    get "/music" => :music
    get "/error" => :error
  end
  controller :albums do
    get "delete_album" => :destroy
  end
  controller :PortfolioTwo do
    get "/home" => :home_page
    get "/show" => :show
  end
  controller :announcements do
    get "delete_message" => :destroy
  end

  root :to => 'flash_home#flash_home',:as=>"flash"

  match "*a" => "flash_home#error"
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :theme_id
  belongs_to :theme
  has_many :images
end

app/controllers/albums_controller.rb
#encoding:utf-8
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  before_filter :authorize ,:except => :index

  def index
    params_theme = {"Wedding tracking" => "婚纱跟拍", "Personalized wedding" => "个性婚纱", "Art Gallery" => "艺术写真", "Makeup show" => "妆面展示"}
    @theme = Theme.find_by_name(params_theme[params[:theme_name]]) ||Theme.find_by_id(params[:theme_id])
   begin
    @albums = @theme.albums.paginate :page=>params[:page]||1,:per_page=>9
  rescue
    redirect_to error_path
   end
    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # error.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new
    @album.theme =Theme.find_by_id(params[:theme_id])
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])
    respond_to do |format|
      if @album.save
        format.html { redirect_to new_album_path(:theme_id=>@album.theme_id), :alert =>  '新相册创建成功' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to :back, :alert=>'修改成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="fi">
  <div class="field">
    <%= f.label :name,  "相册名称"%><br />
    <%= f.text_field :name %>
  </div>

  <div class="field" style="display:none">
    <% f.label :theme_id %><br />
    <%= f.number_field :theme_id %>
  </div>
  <div class="actions">
    <%= f.submit "确定" %>
  </div>
    </div>
<% end %>

app/views/albums/edit.html.erb
<%= render 'form' %>

<%= link_to '回到相册列表', albums_path(:theme_id=>@album.theme) %>

app/views/albums/index.html.erb
</br>
<div class="albums">
  <ul>
    <% @albums.each do |album| %>
        <li>
          <%= link_to show_path(:album_id => album.id), :class => "thumb" do %>
              <% unless  album.images.first.nil? %><%= image_tag album.images.first.photo_url(:thumb),:width => "125px",:height => "150px" %>
                  <% else %><%= image_tag "no_image.jpg" ,:width => "125px",:height => "150px"%>
              <% end %>
          <% end %>
          <div class="album-name">
          <% unless find_user.nil? %>
          <%= link_to "修改相册名称", edit_album_path(album) %>
          <%= link_to "删除相册", delete_album_path(:id => album.id) %>
           <% end %>
         </div>
        <div class="album-name">
        <%= album.name %>
        </div>
        </li>
    <% end %>
  </ul>
  <%= will_paginate @albums,:prev_label=> '上一页',:next_label=> '下一页'%>
</div>
共<%=@albums.total_entries%>条
<br/>

app/views/albums/new.html.erb
<div id="fi">
  <%= render 'form' %>
  <%= link_to '退出', home_path %>
</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Theme:</b>
  <%= @album.theme_id %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>