config/routes.rb
PhotographyStudio::Application.routes.draw do
  resources :announcements
  resources :albums
  resources :images
  get "sessions/new"
  get "sessions/create"

  controller :Users do
    get "admin_edit" => :edit
    post "admin_edit" => :update
    get "admin_show" => :show
    put "admin_edit" => :update
  end
  controller :images do
    get "del_image" => :destroy
  end
 controller :Sessions do
   post "/sessions/new" => :create
   get "login" => :new
   post "login" => :create
   get "logout" => :destroy
 end

  controller :Home do
   get "/home" => :home_page

  end
  controller :FlashHome do
    get "flash" =>:flash_home
    get "/music" => :music
    get "/error" => :error
  end
  controller :albums do
    get "delete_album" => :destroy
  end
  controller :PortfolioTwo do
    get "/home" => :home_page
    get "/show" => :show
  end
  controller :announcements do
    get "delete_message" => :destroy
  end

  root :to => 'flash_home#flash_home',:as=>"flash"

  match "*a" => "flash_home#error"
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :describer, :photo, :album_id,:photo_cache
  mount_uploader :photo, PhotoUploader
  belongs_to :album
end

app/controllers/images_controller.rb
#encoding:utf-8
class ImagesController < ApplicationController
  # GET /images
  # GET /images.
  def index
    @images = Image.order("created_at").paginate :page=>params[:page]||1,:per_page=>9

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # error.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new
    @image.album = Album.find(params[:album_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.jshttp://0.0.0.0:3001on
  def create
    @image = Image.new(params[:image])
    unless @image.album.images.count.eql?(10)


    respond_to do |format|
      if @image.save
        format.html { redirect_to new_image_path(:album_id=>@image.album_id), alert: '保存成功' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to home_path,:alert => "超过图片张数限制"
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, alert: '更新成功' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to home_path,:alert => "删除完成"
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image, :html => {:multipart => true}) do |f| %>
    <% if @image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

          <ul>
            <% @image.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
   <div id="fe">
    <div class="field" >
      <%= f.label :photo,"选择照片"  %>
      <br/>
      <%= f.file_field :photo %>
      <%= f.hidden_field :photo_cache %>
    </div>
    <div style="display:none">
      <%= f.label :album_id %>
      <%= f.number_field :album_id %>
    </div>
    <div class="field">
      <%= f.label :describer,"照片说明" %>
      <br/>
      <%= f.text_field :describer %>
    </div>
    <div class="actions">
      <%= f.submit "上传相片" %>
    </div>
   </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/new.html.erb
<div id="fi" >
<h1>上传照片</h1>
<%= render 'form' %>
<%= link_to '返回相册', show_path(:album_id=>@image.album_id) %>
</div>

app/views/images/show.html.erb
<% unless flash[:notice].nil?%>
<p id="flash"></p>
<% end %>
<p>
  <b>Photo:</b>
  <%= image_tag(@image.photo_url) if @image.photo? %>
</p>


<p>
  <b>Describer:</b>
  <%= @image.describer %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back',  home_path%>